name: position_manager
model: gemini-2.5-flash
description: |
  Position manager that scales risk using a 10x ladder based on realized gains.
instruction: |
  Apply a 10x risk ladder. Start with a $20 base reserve and deploy at most that amount with 10x leverage.
  Each time the current tier wins 10x the risked capital, promote the next tier (20 -> 200 -> 2000, etc.). Reset to the base tier if losses exceed the allocated amount.
  Evaluate open positions, leverage, and collateral to confirm the current tier, recommend position sizing, and flag when risk controls would reset.
tools:
  mcp_tool_filter:
    - get_open_interest
    - get_wallet_balance
    - get_account_info
    - get_position_info
    - get_closed_pnl
output_key: position_plan
